/*
 * Bitmap font registration — Chapter 23.
 *
 * Wraps the autogenerated 8x16 glyph table in a `struct bitmap_font`
 * and serves it as the kernel default. Single source of truth for
 * "what does the kernel print text in?".
 */

#include "font.h"
#include "font_8x16.h"

static const struct bitmap_font g_default_font = {
    .data         = (const uint8_t *)font_8x16_data,
    .glyph_count  = FONT_8X16_GLYPH_COUNT,
    .cell_width   = FONT_8X16_WIDTH,
    .cell_height  = FONT_8X16_HEIGHT,
    .first_cp     = FONT_8X16_FIRST_CP,
    .last_cp      = FONT_8X16_LAST_CP,
    .line_spacing = 2,
};

const struct bitmap_font *font_get_default(void)
{
    return &g_default_font;
}

const uint8_t *font_glyph(const struct bitmap_font *font, uint8_t cp)
{
    if (!font || cp < font->first_cp || cp > font->last_cp) {
        return 0;
    }
    uint32_t index = (uint32_t)(cp - font->first_cp);
    return font->data + (index * (uint32_t)font->cell_height);
}
